{
 "title": "AIBrix Engine Dashboard (vLLM)",
 "description": "Monitoring vLLM Inference Server",
 "tags": [
  "vllm",
  "model"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "model_name", "label": "model_name", "query": { "query": "label_values(model_name)" } }
  ]
 },
 "panels": [
  { "title": "vLLM Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Request Count(Stop)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vllm:request_success_total{finished_reason=\"stop\", model_name=\"$model_name\", job=\"pods\"}[$__range]))",
     "legendFormat": "Success Request Count(stop)"
    }
   ]
  },
  {
   "title": "Success Request Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "sum by(finished_reason) (increase(vllm:request_success_total{model_name=\"$model_name\", job=\"pods\"}[$__range]))",
     "legendFormat": "Success Request Count"
    }
   ]
  },
  {
   "title": "Request Prompt Length",
   "type": "heatmap",
   "description": "Heatmap of request prompt length",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le) (increase(vllm:request_prompt_tokens_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Generation Length",
   "type": "heatmap",
   "description": "Heatmap of request generation length",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le) (increase(vllm:request_generation_tokens_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Prompt & Decode Length",
   "type": "timeseries",
   "description": "Prompt & Decode length",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:request_prompt_tokens_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
     "legendFormat": "Prompt-P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:request_prompt_tokens_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
     "legendFormat": "Prompt-P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:request_prompt_tokens_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
     "legendFormat": "Prompt-P50"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:request_generation_tokens_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
     "legendFormat": "Decode-P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(vllm:request_generation_tokens_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
     "legendFormat": "Decode-P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(vllm:request_generation_tokens_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
     "legendFormat": "Decode-P50"
    }
   ]
  },
  {
   "title": "E2E Request Latency",
   "type": "timeseries",
   "description": "End to end request latency measured in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "avg(rate(vllm:e2e_request_latency_seconds_sum{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])\n/\nrate(vllm:e2e_request_latency_seconds_count{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Time To First Token Latency",
   "type": "timeseries",
   "description": "P50, P90, P95, and P99 TTFT latency in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "avg(rate(vllm:time_to_first_token_seconds_sum{model_name=\"$model_name\",job=\"pods\"}[$__rate_interval])\n/\nrate(vllm:time_to_first_token_seconds_count{model_name=\"$model_name\",job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Time Per Output Token Latency",
   "type": "timeseries",
   "description": "Inter token latency in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "rate(vllm:time_per_output_token_seconds_sum{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])\n/\nrate(vllm:time_per_output_token_seconds_count{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Prompt Token Throughput",
   "type": "timeseries",
   "description": "Number of tokens processed per second",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(vllm:prompt_tokens_total{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "Prompt Tokens/Sec {{model_name}}"
    }
   ]
  },
  {
   "title": "Decode Token Throughput",
   "type": "timeseries",
   "description": "Number of tokens processed per second",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(vllm:generation_tokens_total{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "Generation Tokens/Sec {{pod}}"
    }
   ]
  },
  {
   "title": "Scheduler State",
   "type": "timeseries",
   "description": "Number of requests in RUNNING, WAITING, and SWAPPED state",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(vllm:num_requests_running{model_name=\"$model_name\", job=\"pods\"})",
     "legendFormat": "Num Running"
    },
    {
     "expr": "sum(vllm:num_requests_swapped{model_name=\"$model_name\", job=\"pods\"})",
     "legendFormat": "Num Swapped"
    },
    {
     "expr": "sum(vllm:num_requests_waiting{model_name=\"$model_name\", job=\"pods\"})",
     "legendFormat": "Num Waiting"
    }
   ]
  },
  {
   "title": "Prefix Cache Hit Rate",
   "type": "timeseries",
   "description": "Percentage of prefix cache hit rate",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(vllm:gpu_prefix_cache_hit_rate{model_name=\"$model_name\",job=\"pods\"})",
     "legendFormat": "GPU Prefix Cache Hit Ratio"
    }
   ]
  },
  {
   "title": "Cache Utilization",
   "type": "timeseries",
   "description": "Percentage of used cache blocks by vLLM.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(vllm:gpu_cache_usage_perc{model_name=\"$model_name\", job=\"pods\"})",
     "legendFormat": "GPU Cache Usage"
    },
    {
     "expr": "avg(vllm:cpu_cache_usage_perc{model_name=\"$model_name\", job=\"pods\"})",
     "legendFormat": "CPU Cache Usage"
    }
   ]
  },
  {
   "title": "Finish Reason",
   "type": "timeseries",
   "description": "Number of finished requests by their finish reason: either an EOS token was generated or the max sequence length was reached.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "sum by(finished_reason) (increase(vllm:request_success_total{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KV Cache Offloading - AIBrix Connector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Ops",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(op_type) (increase(vllm:ol_connector_num_ops_total{model_name=\"$model_name\", job=\"pods\"}[$__range]))",
       "legendFormat": "{{op_type}}"
      }
     ]
    },
    {
     "title": "Prefix Length",
     "type": "heatmap",
     "description": "Heatmap of prefix length",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 32 },
     "targets": [
      {
       "expr": "sum by(le, op_type) (increase(vllm:ol_connector_iteration_prefixes_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval]))",
       "legendFormat": "{{op_type}}-{{le}}"
      }
     ]
    },
    {
     "title": "Prefix Length",
     "type": "timeseries",
     "description": "Prefix length",
     "gridPos": { "h": 7, "w": 5, "x": 9, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, op_type) (rate(vllm:ol_connector_iteration_prefixes_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, op_type) (rate(vllm:ol_connector_iteration_prefixes_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le, op_type) (rate(vllm:ol_connector_iteration_prefixes_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P50"
      }
     ]
    },
    {
     "title": "Token Length",
     "type": "heatmap",
     "description": "Heatmap of token length",
     "gridPos": { "h": 7, "w": 5, "x": 14, "y": 32 },
     "targets": [
      {
       "expr": "sum by(le, op_type) (increase(vllm:ol_connector_iteration_tokens_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval]))",
       "legendFormat": "{{op_type}}-{{le}}"
      }
     ]
    },
    {
     "title": "Token Length",
     "type": "timeseries",
     "description": "Token length",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, op_type) (rate(vllm:ol_connector_iteration_tokens_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, op_type) (rate(vllm:ol_connector_iteration_tokens_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le, op_type) (rate(vllm:ol_connector_iteration_tokens_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P50"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "description": "Latency",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, op_type) (rate(vllm:ol_connector_iteration_op_lat_ms_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, op_type) (rate(vllm:ol_connector_iteration_op_lat_ms_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le, op_type) (rate(vllm:ol_connector_iteration_op_lat_ms_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P50"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:ol_connector_iteration_rebuild_lat_ms_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
       "legendFormat": "rebuild_model_input-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:ol_connector_iteration_rebuild_lat_ms_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
       "legendFormat": "rebuild_model_input-P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:ol_connector_iteration_rebuild_lat_ms_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
       "legendFormat": "rebuild_model_input-P50"
      }
     ]
    },
    {
     "title": "Sent Tokens",
     "type": "heatmap",
     "description": "Heatmap of sent tokens",
     "gridPos": { "h": 7, "w": 4, "x": 6, "y": 39 },
     "targets": [
      {
       "expr": "sum by(le, op_type) (increase(vllm:ol_connector_iteration_sent_tokens_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval]))",
       "legendFormat": "{{op_type}}-{{le}}"
      }
     ]
    },
    {
     "title": "Sent Tokens",
     "type": "timeseries",
     "description": "Sent tokens",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, op_type) (rate(vllm:ol_connector_iteration_sent_tokens_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, op_type) (rate(vllm:ol_connector_iteration_sent_tokens_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le, op_type) (rate(vllm:ol_connector_iteration_sent_tokens_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P50"
      }
     ]
    },
    {
     "title": "Received Tokens",
     "type": "heatmap",
     "description": "Heatmap of received tokens",
     "gridPos": { "h": 7, "w": 4, "x": 15, "y": 39 },
     "targets": [
      {
       "expr": "sum by(le, op_type) (increase(vllm:ol_connector_iteration_received_tokens_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval]))",
       "legendFormat": "{{op_type}}-{{le}}"
      }
     ]
    },
    {
     "title": "Received Tokens",
     "type": "timeseries",
     "description": "Received tokens",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, op_type) (rate(vllm:ol_connector_iteration_received_tokens_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, op_type) (rate(vllm:ol_connector_iteration_received_tokens_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le, op_type) (rate(vllm:ol_connector_iteration_received_tokens_bucket{model_name=\"$model_name\", job=\"pods\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P50"
      }
     ]
    }
   ]
  },
  {
   "title": "KV Cache Offloading - Internal - CacheMgr",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Ops",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(op_type) (increase(vllm:kv_cache_ol_num_ops_total{model_name=\"$model_name\", job=\"pods\", cache_type=\"cachemgr\"}[$__range]))",
       "legendFormat": "{{op_type}}"
      }
     ]
    },
    {
     "title": "Prefix Length",
     "type": "timeseries",
     "description": "Prefix length",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_prefixes_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"cachemgr\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_prefixes_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"cachemgr\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_prefixes_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"cachemgr\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P50"
      }
     ]
    },
    {
     "title": "Token Length",
     "type": "timeseries",
     "description": "Token length",
     "gridPos": { "h": 7, "w": 5, "x": 9, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_tokens_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"cachemgr\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_tokens_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"cachemgr\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_tokens_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"cachemgr\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P50"
      }
     ]
    },
    {
     "title": "Fetched Tokens",
     "type": "timeseries",
     "description": "Fetched tokens",
     "gridPos": { "h": 7, "w": 5, "x": 14, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_fetched_tokens_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"cachemgr\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_fetched_tokens_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"cachemgr\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_fetched_tokens_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"cachemgr\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P50"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "description": "Latency",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_op_lat_ms_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"cachemgr\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_op_lat_ms_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"cachemgr\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_op_lat_ms_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"cachemgr\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P50"
      }
     ]
    }
   ]
  },
  {
   "title": "KV Cache Offloading - Internal - L1Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Ops",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(op_type) (increase(vllm:kv_cache_ol_num_ops_total{model_name=\"$model_name\", job=\"pods\", cache_type=\"l1cache\"}[$__range]))",
       "legendFormat": "{{op_type}}"
      }
     ]
    },
    {
     "title": "Prefix Length",
     "type": "timeseries",
     "description": "Prefix length",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_prefixes_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l1cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_prefixes_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l1cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_prefixes_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l1cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P50"
      }
     ]
    },
    {
     "title": "Token Length",
     "type": "timeseries",
     "description": "Token length",
     "gridPos": { "h": 7, "w": 5, "x": 9, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_tokens_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l1cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_tokens_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l1cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_tokens_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l1cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P50"
      }
     ]
    },
    {
     "title": "Fetched Tokens",
     "type": "timeseries",
     "description": "Fetched tokens",
     "gridPos": { "h": 7, "w": 5, "x": 14, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_fetched_tokens_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l1cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_fetched_tokens_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l1cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_fetched_tokens_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l1cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P50"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "description": "Latency",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_op_lat_ms_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l1cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_op_lat_ms_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l1cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_op_lat_ms_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l1cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P50"
      }
     ]
    }
   ]
  },
  {
   "title": "KV Cache Offloading - Internal - L2Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Ops",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(op_type) (increase(vllm:kv_cache_ol_num_ops_total{model_name=\"$model_name\", job=\"pods\", cache_type=\"l2cache\"}[$__range]))",
       "legendFormat": "{{op_type}}"
      }
     ]
    },
    {
     "title": "Prefix Length",
     "type": "timeseries",
     "description": "Prefix length",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_prefixes_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l2cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_prefixes_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l2cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_prefixes_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l2cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P50"
      }
     ]
    },
    {
     "title": "Token Length",
     "type": "timeseries",
     "description": "Token length",
     "gridPos": { "h": 7, "w": 5, "x": 9, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_tokens_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l2cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_tokens_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l2cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_tokens_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l2cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P50"
      }
     ]
    },
    {
     "title": "Fetched Tokens",
     "type": "timeseries",
     "description": "Fetched tokens",
     "gridPos": { "h": 7, "w": 5, "x": 14, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_fetched_tokens_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l2cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_fetched_tokens_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l2cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_fetched_tokens_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l2cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P50"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "description": "Latency",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_op_lat_ms_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l2cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P99"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_op_lat_ms_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l2cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le, op_type) (rate(vllm:kv_cache_ol_iteration_op_lat_ms_bucket{model_name=\"$model_name\", job=\"pods\", cache_type=\"l2cache\"}[$__rate_interval])))",
       "legendFormat": "{{op_type}}-P50"
      }
     ]
    }
   ]
  }
 ]
}